# Generated by Django 5.2.15 on 2026-06-10 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_description_and_more'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='campaign',
            field=models.ForeignKey(help_text='The campaign (landing page) this lead came from', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='consent',
            field=models.BooleanField(default=False, help_text='True if the lead explicitly consented to being contacted'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extra form fields not mapped to core columns (future campaigns)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='form_location',
            field=models.CharField(blank=True, help_text='Which form on the page: hero | popup | footer | etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='True if another lead with the same email+campaign exists in the last 24 hours'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal sales notes — not visible to the lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reply_email_sent',
            field=models.BooleanField(default=False, help_text='True if the auto-reply email was sent to the lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sales_email_sent',
            field=models.BooleanField(default=False, help_text='True if the sales notification email was sent successfully'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sheets_synced',
            field=models.BooleanField(default=False, help_text='True if this lead was successfully pushed to Google Sheets'),
        ),
        migrations.AlterField(
            model_name='rfqfile',
            name='file_size',
            field=models.PositiveIntegerField(help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='rfqfile',
            name='original_name',
            field=models.CharField(help_text='Original filename as uploaded by the user', max_length=255),
        ),
    ]
