# Generated by Django 5.2.15 on 2026-06-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_campaign_alter_lead_consent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='reply_email_sent',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sales_email_sent',
        ),
    ]
