# Generated by Django 6.0.5 on 2026-06-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_email_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='sheets_synced',
        ),
    ]
