# Generated by Django 5.2.15 on 2026-06-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, help_text='Internal notes about this campaign'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fields_config',
            field=models.JSONField(blank=True, default=dict, help_text='Controls which optional fields are required/optional/hidden for this campaign. Example: {"company": "required", "phone": "required", "country": "optional", "industry": "required", "requirement_type": "optional", "file_upload": "optional"}'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive campaigns reject form submissions with a 400 error'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(help_text="Human-readable campaign name, e.g. 'Oil & Gas Landing Page'", max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(help_text="URL-friendly identifier, e.g. 'oil-gas-landing'", unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='url',
            field=models.URLField(blank=True, help_text='Public URL of the landing page (for reference only)'),
        ),
    ]
