# Generated by Django 6.0.5 on 2026-06-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='sheets_id',
        ),
    ]
